# Copyright DB InfraGO AG and contributors
# SPDX-License-Identifier: CC0-1.0

default_install_hook_types: [commit-msg, pre-commit]
default_stages: [pre-commit, pre-merge-commit]
default_language_version:
    node: 20.17.0
minimum_pre_commit_version: 3.2.0
repos:
  - repo: https://github.com/gitleaks/gitleaks.git
    rev: v8.21.1
    hooks:
      - id: gitleaks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-toml
      - id: check-vcs-permalinks
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: destroyed-symlinks
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: trailing-whitespace
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.5
    hooks:
      - id: insert-license
        name: Insert Apache license headers (shell-style comments)
        files: '(?:^|/)(?:.*\.(?:py|sh|toml|ya?ml)|Dockerfile|Makefile)$'
        exclude: '(?:^|/)\..+|^docs/Makefile$'
        args:
          - --detect-license-in-X-top-lines=15
          - --license-filepath
          - LICENSES/.license_header_apache.txt
          - --comment-style
          - '#'
      - id: insert-license
        name: Insert CC0 license headers (shell-style comments)
        files: '(?:^|/)(?:codeql-analysis.yml|dependabot.yml|\.(?:pre-commit-config.yaml|(?:git|helm|docker)ignore))$'
        args:
          - --detect-license-in-X-top-lines=15
          - --license-filepath
          - LICENSES/.license_header_cc0.txt
          - --comment-style
          - '#'
      - id: insert-license
        name: Insert license headers (HTML and Markdown)
        files: '\.(?:html|md)$'
        exclude: '(?:^|/)\..+'
        args:
          - --detect-license-in-X-top-lines=15
          - --license-filepath
          - LICENSES/.license_header_apache.txt
          - --comment-style
          - '<!--| ~| -->'
      # - id: insert-license
      #   name: Insert license headers (XML)
      #   files: '\.xml$'
      #   exclude: '(?:^|/)\..+'
      #   args:
      #     - --detect-license-in-X-top-lines=15
      #     - --license-filepath
      #     - LICENSES/.license_header_apache.txt
      #     - --comment-style
      #     - '<!--| ~| -->'
      #     - --insert-license-after-regex
      #     - '^<\\?\\s*[^>]*\\?>'
      - id: insert-license
        name: Insert Apache license headers (C-style comments)
        files: '\.(?:s?css|js|ts)$'
        exclude: '(?:^|/)\..+'
        args:
          - --detect-license-in-X-top-lines=15
          - --license-filepath
          - LICENSES/.license_header_apache.txt
          - --comment-style
          - '/*| *| */'
      - id: insert-license
        name: Insert Apache license headers (Java-style comments)
        files: '\.java$'
        exclude: '(?:^|/)\..+'
        args:
          - --detect-license-in-X-top-lines=15
          - --license-filepath
          - LICENSES/.license_header_apache.txt
          - --comment-style
          - '//'
      - id: insert-license
        name: Insert Apache license headers (reST comments)
        files: '\.rst$'
        exclude: '(?:^|/)\..+'
        args:
          - --detect-license-in-X-top-lines=15
          - --license-filepath
          - LICENSES/.license_header_apache.txt
          - --comment-style
          - '..|  |'
  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
  - repo: https://github.com/PyCQA/docformatter
    rev: eb1df347edd128b30cd3368dddc3aa65edcfac38
    hooks:
      - id: docformatter
        additional_dependencies:
          - docformatter[tomli]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.7.0
    hooks:
      - id: ruff-format
      - id: ruff
        args: [--extend-ignore=FIX]
  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.12.0
    hooks:
      - id: mypy
  - repo: https://github.com/fsfe/reuse-tool
    rev: 7bdfa5462e2816bd730e7d619f19773b33d7761b
    hooks:
      - id: reuse-lint-file
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.18.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies:
          - '@commitlint/config-conventional'
  - repo: https://github.com/hadolint/hadolint
    rev: v2.13.1-beta
    hooks:
      - id: hadolint-docker
