// Copyright DB InfraGO AG and contributors
// SPDX-License-Identifier: Apache-2.0

/*
 * Capella API
 * API to access live data and modify Capella projects
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.db.capella.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.v3.oas.annotations.media.Schema;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;

/**
 * A diagram editor in Capella
 */
@Schema(description = "A diagram editor in Capella")
@JsonPropertyOrder({
  DiagramEditor.JSON_PROPERTY_ID,
  DiagramEditor.JSON_PROPERTY_NAME,
  DiagramEditor.JSON_PROPERTY_URI
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaJerseyServerCodegen", comments = "Generator version: 7.9.0")
public class DiagramEditor   {
  public static final String JSON_PROPERTY_ID = "id";
  @JsonProperty(JSON_PROPERTY_ID)
  private String id;

  public static final String JSON_PROPERTY_NAME = "name";
  @JsonProperty(JSON_PROPERTY_NAME)
  private String name;

  public static final String JSON_PROPERTY_URI = "uri";
  @JsonProperty(JSON_PROPERTY_URI)
  private String uri;

  public DiagramEditor id(String id) {
    this.id = id;
    return this;
  }

  /**
   * Unique identifier of the diagram
   * @return id
   **/
  @JsonProperty(value = "id")
  @Schema(description = "Unique identifier of the diagram")

  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public DiagramEditor name(String name) {
    this.name = name;
    return this;
  }

  /**
   * Name of the diagram
   * @return name
   **/
  @JsonProperty(value = "name")
  @Schema(description = "Name of the diagram")

  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public DiagramEditor uri(String uri) {
    this.uri = uri;
    return this;
  }

  /**
   * URI of the diagram
   * @return uri
   **/
  @JsonProperty(value = "uri")
  @Schema(description = "URI of the diagram")

  public String getUri() {
    return uri;
  }

  public void setUri(String uri) {
    this.uri = uri;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DiagramEditor diagramEditor = (DiagramEditor) o;
    return Objects.equals(this.id, diagramEditor.id) &&
        Objects.equals(this.name, diagramEditor.name) &&
        Objects.equals(this.uri, diagramEditor.uri);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, uri);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DiagramEditor {\n");

    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    uri: ").append(toIndentedString(uri)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
