/*
 * Capella API
 * API to access live data and modify Capella projects
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.db.capella.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.v3.oas.annotations.media.Schema;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;

/**
 * A diagram
 */
@Schema(description = "A diagram")
@JsonPropertyOrder({
  Diagram.JSON_PROPERTY_ID,
  Diagram.JSON_PROPERTY_NAME,
  Diagram.JSON_PROPERTY_DESCRIPTION,
  Diagram.JSON_PROPERTY_DOCUMENTATION
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaJerseyServerCodegen", comments = "Generator version: 7.7.0")
public class Diagram   {
  public static final String JSON_PROPERTY_ID = "id";
  @JsonProperty(JSON_PROPERTY_ID)
  private String id;

  public static final String JSON_PROPERTY_NAME = "name";
  @JsonProperty(JSON_PROPERTY_NAME)
  private String name;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  private String description;

  public static final String JSON_PROPERTY_DOCUMENTATION = "documentation";
  @JsonProperty(JSON_PROPERTY_DOCUMENTATION)
  private String documentation;

  public Diagram id(String id) {
    this.id = id;
    return this;
  }

  /**
   * Unique identifier of the diagram
   * @return id
   **/
  @JsonProperty(value = "id")
  @Schema(description = "Unique identifier of the diagram")
  
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public Diagram name(String name) {
    this.name = name;
    return this;
  }

  /**
   * Name of the diagram
   * @return name
   **/
  @JsonProperty(value = "name")
  @Schema(description = "Name of the diagram")
  
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Diagram description(String description) {
    this.description = description;
    return this;
  }

  /**
   * Description of the diagram
   * @return description
   **/
  @JsonProperty(value = "description")
  @Schema(description = "Description of the diagram")
  
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public Diagram documentation(String documentation) {
    this.documentation = documentation;
    return this;
  }

  /**
   * Documentation of the diagram
   * @return documentation
   **/
  @JsonProperty(value = "documentation")
  @Schema(description = "Documentation of the diagram")
  
  public String getDocumentation() {
    return documentation;
  }

  public void setDocumentation(String documentation) {
    this.documentation = documentation;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Diagram diagram = (Diagram) o;
    return Objects.equals(this.id, diagram.id) &&
        Objects.equals(this.name, diagram.name) &&
        Objects.equals(this.description, diagram.description) &&
        Objects.equals(this.documentation, diagram.documentation);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, description, documentation);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Diagram {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    documentation: ").append(toIndentedString(documentation)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

