/*
 * Capella API
 * API to access live data and modify Capella projects
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.db.capella.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.v3.oas.annotations.media.Schema;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;

/**
 * An abstract model object
 */
@Schema(description = "An abstract model object")
@JsonPropertyOrder({
  EObject.JSON_PROPERTY_D_U_M_M_Y
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaJerseyServerCodegen", comments = "Generator version: 7.7.0")
public class EObject   {
  public static final String JSON_PROPERTY_D_U_M_M_Y = "DUMMY";
  @JsonProperty(JSON_PROPERTY_D_U_M_M_Y)
  private String DUMMY;

  public EObject DUMMY(String DUMMY) {
    this.DUMMY = DUMMY;
    return this;
  }

  /**
   * Dummy property
   * @return DUMMY
   **/
  @JsonProperty(value = "DUMMY")
  @Schema(description = "Dummy property")
  
  public String getDUMMY() {
    return DUMMY;
  }

  public void setDUMMY(String DUMMY) {
    this.DUMMY = DUMMY;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EObject eobject = (EObject) o;
    return Objects.equals(this.DUMMY, eobject.DUMMY);
  }

  @Override
  public int hashCode() {
    return Objects.hash(DUMMY);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EObject {\n");
    
    sb.append("    DUMMY: ").append(toIndentedString(DUMMY)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

