// Copyright DB InfraGO AG and contributors
// SPDX-License-Identifier: Apache-2.0

/*
 * Capella API
 * API to access live data and modify Capella projects
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.db.capella.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.v3.oas.annotations.media.Schema;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;

/**
 * Common base for all capella elements  [source: capella study]  Used in levels: operational,system,logical,physical,epbs
 */
@Schema(description = "Common base for all capella elements  [source: capella study]  Used in levels: operational,system,logical,physical,epbs")
@JsonPropertyOrder({
  ModelElement.JSON_PROPERTY_ID,
  ModelElement.JSON_PROPERTY_SID,
  ModelElement.JSON_PROPERTY_D_U_M_M_Y
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaJerseyServerCodegen", comments = "Generator version: 7.9.0")
public class ModelElement   {
  public static final String JSON_PROPERTY_ID = "id";
  @JsonProperty(JSON_PROPERTY_ID)
  private String id;

  public static final String JSON_PROPERTY_SID = "sid";
  @JsonProperty(JSON_PROPERTY_SID)
  private String sid;

  public static final String JSON_PROPERTY_D_U_M_M_Y = "DUMMY";
  @JsonProperty(JSON_PROPERTY_D_U_M_M_Y)
  private String DUMMY;

  public ModelElement id(String id) {
    this.id = id;
    return this;
  }

  /**
   * The unique identifier for this element  [source: capella study]
   * @return id
   **/
  @JsonProperty(value = "id")
  @Schema(description = "The unique identifier for this element  [source: capella study]")

  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public ModelElement sid(String sid) {
    this.sid = sid;
    return this;
  }

  /**
   * The unique system identifier for this element
   * @return sid
   **/
  @JsonProperty(value = "sid")
  @Schema(description = "The unique system identifier for this element")

  public String getSid() {
    return sid;
  }

  public void setSid(String sid) {
    this.sid = sid;
  }

  public ModelElement DUMMY(String DUMMY) {
    this.DUMMY = DUMMY;
    return this;
  }

  /**
   * Dummy property
   * @return DUMMY
   **/
  @JsonProperty(value = "DUMMY")
  @Schema(description = "Dummy property")

  public String getDUMMY() {
    return DUMMY;
  }

  public void setDUMMY(String DUMMY) {
    this.DUMMY = DUMMY;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ModelElement modelElement = (ModelElement) o;
    return Objects.equals(this.id, modelElement.id) &&
        Objects.equals(this.sid, modelElement.sid) &&
        Objects.equals(this.DUMMY, modelElement.DUMMY);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, sid, DUMMY);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ModelElement {\n");

    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    sid: ").append(toIndentedString(sid)).append("\n");
    sb.append("    DUMMY: ").append(toIndentedString(DUMMY)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
