/*
 * Capella API
 * API to access live data and modify Capella projects
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.db.capella.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.v3.oas.annotations.media.Schema;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;

/**
 * A generic resource
 */
@Schema(description = "A generic resource")
@JsonPropertyOrder({
  Resource.JSON_PROPERTY_FULL_PATH,
  Resource.JSON_PROPERTY_LOCATION,
  Resource.JSON_PROPERTY_NAME
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaJerseyServerCodegen", comments = "Generator version: 7.7.0")
public class Resource   {
  public static final String JSON_PROPERTY_FULL_PATH = "fullPath";
  @JsonProperty(JSON_PROPERTY_FULL_PATH)
  private String fullPath;

  public static final String JSON_PROPERTY_LOCATION = "location";
  @JsonProperty(JSON_PROPERTY_LOCATION)
  private String location;

  public static final String JSON_PROPERTY_NAME = "name";
  @JsonProperty(JSON_PROPERTY_NAME)
  private String name = "";

  public Resource fullPath(String fullPath) {
    this.fullPath = fullPath;
    return this;
  }

  /**
   * Full, absolute path of the resource relative to the workspace. A resource&#39;s full path indicates the route from the root of the workspace to the resource.  Within a workspace, there is exactly one such path for any given resource. The first segment of these paths name a project; remaining segments, folders and/or files within that project. The returned path never has a trailing separator. 
   * @return fullPath
   **/
  @JsonProperty(value = "fullPath")
  @Schema(description = "Full, absolute path of the resource relative to the workspace. A resource's full path indicates the route from the root of the workspace to the resource.  Within a workspace, there is exactly one such path for any given resource. The first segment of these paths name a project; remaining segments, folders and/or files within that project. The returned path never has a trailing separator. ")
  
  public String getFullPath() {
    return fullPath;
  }

  public void setFullPath(String fullPath) {
    this.fullPath = fullPath;
  }

  public Resource location(String location) {
    this.location = location;
    return this;
  }

  /**
   * Location of the resource in the file system
   * @return location
   **/
  @JsonProperty(value = "location")
  @Schema(description = "Location of the resource in the file system")
  
  public String getLocation() {
    return location;
  }

  public void setLocation(String location) {
    this.location = location;
  }

  public Resource name(String name) {
    this.name = name;
    return this;
  }

  /**
   * Name of the resource. The workspace root&#39;s name is the empty string. 
   * @return name
   **/
  @JsonProperty(value = "name")
  @Schema(description = "Name of the resource. The workspace root's name is the empty string. ")
  
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Resource resource = (Resource) o;
    return Objects.equals(this.fullPath, resource.fullPath) &&
        Objects.equals(this.location, resource.location) &&
        Objects.equals(this.name, resource.name);
  }

  @Override
  public int hashCode() {
    return Objects.hash(fullPath, location, name);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Resource {\n");
    
    sb.append("    fullPath: ").append(toIndentedString(fullPath)).append("\n");
    sb.append("    location: ").append(toIndentedString(location)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

