// Copyright DB InfraGO AG and contributors
// SPDX-License-Identifier: Apache-2.0

/*
 * Capella API
 * API to access live data and modify Capella projects
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.db.capella.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.v3.oas.annotations.media.Schema;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;

/**
 * The selected Capella model element
 */
@Schema(description = "The selected Capella model element")
@JsonPropertyOrder({
  SelectedModelElement.JSON_PROPERTY_NAME,
  SelectedModelElement.JSON_PROPERTY_DESCRIPTION,
  SelectedModelElement.JSON_PROPERTY_TYPE,
  SelectedModelElement.JSON_PROPERTY_ID,
  SelectedModelElement.JSON_PROPERTY_SID,
  SelectedModelElement.JSON_PROPERTY_D_U_M_M_Y
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaJerseyServerCodegen", comments = "Generator version: 7.9.0")
public class SelectedModelElement   {
  public static final String JSON_PROPERTY_NAME = "name";
  @JsonProperty(JSON_PROPERTY_NAME)
  private String name;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  private String description;

  public static final String JSON_PROPERTY_TYPE = "type";
  @JsonProperty(JSON_PROPERTY_TYPE)
  private String type;

  public static final String JSON_PROPERTY_ID = "id";
  @JsonProperty(JSON_PROPERTY_ID)
  private String id;

  public static final String JSON_PROPERTY_SID = "sid";
  @JsonProperty(JSON_PROPERTY_SID)
  private String sid;

  public static final String JSON_PROPERTY_D_U_M_M_Y = "DUMMY";
  @JsonProperty(JSON_PROPERTY_D_U_M_M_Y)
  private String DUMMY;

  public SelectedModelElement name(String name) {
    this.name = name;
    return this;
  }

  /**
   * The name of the selected element
   * @return name
   **/
  @JsonProperty(value = "name")
  @Schema(description = "The name of the selected element")

  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public SelectedModelElement description(String description) {
    this.description = description;
    return this;
  }

  /**
   * The description of the selected element
   * @return description
   **/
  @JsonProperty(value = "description")
  @Schema(description = "The description of the selected element")

  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public SelectedModelElement type(String type) {
    this.type = type;
    return this;
  }

  /**
   * The type of the selected element
   * @return type
   **/
  @JsonProperty(value = "type")
  @Schema(description = "The type of the selected element")

  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public SelectedModelElement id(String id) {
    this.id = id;
    return this;
  }

  /**
   * The unique identifier for this element  [source: capella study]
   * @return id
   **/
  @JsonProperty(value = "id")
  @Schema(description = "The unique identifier for this element  [source: capella study]")

  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public SelectedModelElement sid(String sid) {
    this.sid = sid;
    return this;
  }

  /**
   * The unique system identifier for this element
   * @return sid
   **/
  @JsonProperty(value = "sid")
  @Schema(description = "The unique system identifier for this element")

  public String getSid() {
    return sid;
  }

  public void setSid(String sid) {
    this.sid = sid;
  }

  public SelectedModelElement DUMMY(String DUMMY) {
    this.DUMMY = DUMMY;
    return this;
  }

  /**
   * Dummy property
   * @return DUMMY
   **/
  @JsonProperty(value = "DUMMY")
  @Schema(description = "Dummy property")

  public String getDUMMY() {
    return DUMMY;
  }

  public void setDUMMY(String DUMMY) {
    this.DUMMY = DUMMY;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SelectedModelElement selectedModelElement = (SelectedModelElement) o;
    return Objects.equals(this.name, selectedModelElement.name) &&
        Objects.equals(this.description, selectedModelElement.description) &&
        Objects.equals(this.type, selectedModelElement.type) &&
        Objects.equals(this.id, selectedModelElement.id) &&
        Objects.equals(this.sid, selectedModelElement.sid) &&
        Objects.equals(this.DUMMY, selectedModelElement.DUMMY);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, description, type, id, sid, DUMMY);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SelectedModelElement {\n");

    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    sid: ").append(toIndentedString(sid)).append("\n");
    sb.append("    DUMMY: ").append(toIndentedString(DUMMY)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
