/*
 * Capella API
 * API to access live data and modify Capella projects
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.db.capella.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.v3.oas.annotations.media.Schema;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;

/**
 * A workspace project
 */
@Schema(description = "A workspace project")
@JsonPropertyOrder({
  WorkspaceProject.JSON_PROPERTY_OPEN,
  WorkspaceProject.JSON_PROPERTY_MODIFIED,
  WorkspaceProject.JSON_PROPERTY_FULL_PATH,
  WorkspaceProject.JSON_PROPERTY_LOCATION,
  WorkspaceProject.JSON_PROPERTY_NAME
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaJerseyServerCodegen", comments = "Generator version: 7.7.0")
public class WorkspaceProject   {
  public static final String JSON_PROPERTY_OPEN = "open";
  @JsonProperty(JSON_PROPERTY_OPEN)
  private Boolean open;

  public static final String JSON_PROPERTY_MODIFIED = "modified";
  @JsonProperty(JSON_PROPERTY_MODIFIED)
  private Boolean modified = false;

  public static final String JSON_PROPERTY_FULL_PATH = "fullPath";
  @JsonProperty(JSON_PROPERTY_FULL_PATH)
  private String fullPath;

  public static final String JSON_PROPERTY_LOCATION = "location";
  @JsonProperty(JSON_PROPERTY_LOCATION)
  private String location;

  public static final String JSON_PROPERTY_NAME = "name";
  @JsonProperty(JSON_PROPERTY_NAME)
  private String name = "";

  public WorkspaceProject open(Boolean open) {
    this.open = open;
    return this;
  }

  /**
   * Whether the project is open or not
   * @return open
   **/
  @JsonProperty(value = "open")
  @Schema(description = "Whether the project is open or not")
  
  public Boolean getOpen() {
    return open;
  }

  public void setOpen(Boolean open) {
    this.open = open;
  }

  public WorkspaceProject modified(Boolean modified) {
    this.modified = modified;
    return this;
  }

  /**
   * Whether the project is in a dirty (unsaved changes) state or not
   * @return modified
   **/
  @JsonProperty(value = "modified")
  @Schema(description = "Whether the project is in a dirty (unsaved changes) state or not")
  
  public Boolean getModified() {
    return modified;
  }

  public void setModified(Boolean modified) {
    this.modified = modified;
  }

  public WorkspaceProject fullPath(String fullPath) {
    this.fullPath = fullPath;
    return this;
  }

  /**
   * Full, absolute path of the resource relative to the workspace. A resource&#39;s full path indicates the route from the root of the workspace to the resource.  Within a workspace, there is exactly one such path for any given resource. The first segment of these paths name a project; remaining segments, folders and/or files within that project. The returned path never has a trailing separator. 
   * @return fullPath
   **/
  @JsonProperty(value = "fullPath")
  @Schema(description = "Full, absolute path of the resource relative to the workspace. A resource's full path indicates the route from the root of the workspace to the resource.  Within a workspace, there is exactly one such path for any given resource. The first segment of these paths name a project; remaining segments, folders and/or files within that project. The returned path never has a trailing separator. ")
  
  public String getFullPath() {
    return fullPath;
  }

  public void setFullPath(String fullPath) {
    this.fullPath = fullPath;
  }

  public WorkspaceProject location(String location) {
    this.location = location;
    return this;
  }

  /**
   * Location of the resource in the file system
   * @return location
   **/
  @JsonProperty(value = "location")
  @Schema(description = "Location of the resource in the file system")
  
  public String getLocation() {
    return location;
  }

  public void setLocation(String location) {
    this.location = location;
  }

  public WorkspaceProject name(String name) {
    this.name = name;
    return this;
  }

  /**
   * Name of the resource. The workspace root&#39;s name is the empty string. 
   * @return name
   **/
  @JsonProperty(value = "name")
  @Schema(description = "Name of the resource. The workspace root's name is the empty string. ")
  
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WorkspaceProject workspaceProject = (WorkspaceProject) o;
    return Objects.equals(this.open, workspaceProject.open) &&
        Objects.equals(this.modified, workspaceProject.modified) &&
        Objects.equals(this.fullPath, workspaceProject.fullPath) &&
        Objects.equals(this.location, workspaceProject.location) &&
        Objects.equals(this.name, workspaceProject.name);
  }

  @Override
  public int hashCode() {
    return Objects.hash(open, modified, fullPath, location, name);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WorkspaceProject {\n");
    
    sb.append("    open: ").append(toIndentedString(open)).append("\n");
    sb.append("    modified: ").append(toIndentedString(modified)).append("\n");
    sb.append("    fullPath: ").append(toIndentedString(fullPath)).append("\n");
    sb.append("    location: ").append(toIndentedString(location)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

