# Copyright DB InfraGO AG and contributors
# SPDX-License-Identifier: Apache-2.0

openapi: 3.0.3
info:
  title: Capella API
  description: API to access live data and modify Capella projects
  version: 0.0.1
servers:
  - url: http://localhost:5007/api/v1
    description: Embedded Capella REST API server
tags:
  - name: Diagrams
    description: >
      Operations related to diagrams in a Capella model
  - name: Logical Architectures
    description: >
      Operations related to logical architecture layers in a Capella model
  - name: Projects
    description: >
      Operations related to projects in the current workspace in Capella
paths:
  /projects:
    get:
      tags:
        - Projects
      summary: List all projects in the workspace
      operationId: listProjects
      responses:
        '200':
          description: A list of projects
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/WorkspaceProject'
    post:
      tags:
        - Projects
      summary: Import a project into the workspace
      operationId: importProject
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - location
              properties:
                location:
                  type: string
                  description: >
                    Absolute path of the project folder in the local file
                    system
      responses:
        '201':
          description: Project imported successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkspaceProject'
        '400':
          description: Invalid request
        '404':
          description: Project not found
        '409':
          description: Project already exists in the workspace
  /projects/{project_name}:
    get:
      tags:
        - Projects
      summary: Get a project by name
      operationId: getProjectByName
      parameters:
        - name: project_name
          in: path
          required: true
          description: Unique name of the project
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkspaceProject'
        '404':
          description: Project not found
    delete:
      tags:
        - Projects
      summary: Delete a project by name
      operationId: deleteProjectByName
      parameters:
        - name: project_name
          in: path
          required: true
          description: Unique name of the project to be deleted
          schema:
            type: string
        - name: deleteContents
          in: query
          required: false
          description: >
            Whether to delete the project contents on disk (cannot be undone)
            or not
          schema:
            type: boolean
            default: false
      responses:
        '200':
          description: Project deleted successfully
        '404':
          description: Project not found
  /projects/{project_name}/close:
    post:
      tags:
        - Projects
      summary: Close a project by name
      operationId: closeProjectByName
      parameters:
        - name: project_name
          in: path
          required: true
          description: Unique name of the project to be closed
          schema:
            type: string
      responses:
        '200':
          description: Project closed successfully
        '404':
          description: Project not found
  /projects/{project_name}/open:
    post:
      tags:
        - Projects
      summary: Open a project by name
      operationId: openProjectByName
      parameters:
        - name: project_name
          in: path
          required: true
          description: Unique name of the project to be opened
          schema:
            type: string
      responses:
        '200':
          description: Project opened successfully
        '404':
          description: Project not found
  /projects/{project_name}/save:
    post:
      tags:
        - Projects
      summary: Save a project by name
      operationId: saveProjectByName
      parameters:
        - name: project_name
          in: path
          required: true
          description: Unique name of the project to be saved
          schema:
            type: string
      responses:
        '200':
          description: Project saved successfully
        '404':
          description: Project not found
  /projects/{project_name}/diagram-editors:
    get:
      tags:
        - Diagrams
      summary: Get a list of all open diagram editors for a project by name
      operationId: getDiagramEditorsByProjectName
      parameters:
        - name: project_name
          in: path
          required: true
          description: Unique name of the project
          schema:
            type: string
      responses:
        '200':
          description: A list of open diagram editors
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DiagramEditor'
        '404':
          description: Project not found
  /projects/{project_name}/diagrams:
    get:
      tags:
        - Diagrams
      summary: Get a list of all diagrams for a project by name
      operationId: getDiagramsByProjectName
      parameters:
        - name: project_name
          in: path
          required: true
          description: Unique name of the project
          schema:
            type: string
      responses:
        '200':
          description: A list of diagrams
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Diagram'
        '404':
          description: Project not found
components:
  schemas:
    Diagram:
      type: object
      description: A diagram
      properties:
        id:
          type: string
          description: Unique identifier of the diagram
        name:
          type: string
          description: Name of the diagram
        description:
          type: string
          description: Description of the diagram
        documentation:
          type: string
          description: Documentation of the diagram
    DiagramEditor:
      type: object
      description: A diagram editor in Capella
      properties:
        id:
          type: string
          description: Unique identifier of the diagram
        name:
          type: string
          description: Name of the diagram
        uri:
          type: string
          description: URI of the diagram
    EObject:
      type: object
      description: An abstract model object
      properties:
        DUMMY:
          type: string
          description: Dummy property
    Element:
      type: object
      description: An element
      allOf:
        - $ref: '#/components/schemas/EObject'
    ExtensibleElement:
      type: object
      description: An extensible element
      allOf:
        - $ref: '#/components/schemas/Element'
    ModelElement:
      type: object
      description: "Common base for all capella elements\r\n[source: capella study]\n\
        \nUsed in levels: operational,system,logical,physical,epbs"
      allOf:
      - $ref: '#/components/schemas/ExtensibleElement'
      properties:
        id:
          type: string
          description: "The unique identifier for this element\r\n[source: capella\
            \ study]"
        sid:
          type: string
          description: The unique system identifier for this element
    Resource:
      type: object
      description: A generic resource
      properties:
        fullPath:
          type: string
          description: >
            Full, absolute path of the resource relative to the workspace. A
            resource's full path indicates the route from the root of the
            workspace to the resource.  Within a workspace, there is exactly
            one such path for any given resource. The first segment of these
            paths name a project; remaining segments, folders and/or files
            within that project. The returned path never has a trailing
            separator.
        location:
          type: string
          description: Location of the resource in the file system
        name:
          type: string
          default: ''
          description: >
            Name of the resource. The workspace root's name is the empty
            string.
    WorkspaceProject:
      type: object
      description: A workspace project
      allOf:
        - $ref: '#/components/schemas/Resource'
      properties:
        open:
          type: boolean
          description: Whether the project is open or not
        modified:
          type: boolean
          description: Whether the project is in a dirty (unsaved changes) state or not
          default: false
